LICENSE
Updated the copyright.
Reviewed by NOBODY (OOPS!).
Apple started contribution in 2013: http://commits.webkit.org/r156073.
Google contributed in 2017: https://commits.webkit.org/r216706 through https://commits.webkit.org/r222534.
* LICENSE:
=> Updated the copyright.

resources/benchmark-runner.js
Also deleted the unused _waitAndWarmUp.
=> Delete SimplePromise and use regular native Promise.

InteractiveRunner.html, resources/benchmark-report.js, resources/benchmark-runner.js, resources/main.js, resources/tests.js
This is the first, format and  function preserving PR to start the ES6.
- Convert var to let/const
- Use arrow functions where possible
=> Basic ES6 conversions: let/const and arrow functions

resources/benchmark-runner.mjs
Sort BenchmarRunner run methods in chronological order.
=> Move BenchmarkRunner methods

resources/tests.mjs
Embarrassingly, I blundered my style fixups and unthinkingly pushed them up without proper testing.
=> Unbreak react-stockcharts tests

package-lock.json, package.json, tests/run.mjs
This PR adds minimal command line options.
=> Add command-line options to tests/run.mjs

index.html, resources/main.css, resources/main.mjs
- Add "Download JSON" button to details view
- Add "Copy JSON" button to details view
- Example JSON result file name: "speedometer_3-2023-02-13T09_18_32.318Z.json"
- Update CSS formatting to make details button all the same width
- Add "title" to results buttons (both summary and details)
=> Add buttons to download and copy JSON  results

index.html, resources/main.css
Make sure we load the hi-res background images in all cases:
- Use srcset for logo
- Use image-set for gauge CSS
=> Use 2x logo and gauge png

resources/main.css, resources/main.mjs, resources/params.mjs
- Use params directly in MainBenchmarkClient
- Remove params.unit
- Update summary only with score
- Update details view with ms value
- Fix gauge background on chrome by also adding `-webkit-image-set(..)`
=> Fix score view

resources/tests.mjs
we are using DeletingItems & DeletingAllItems for the todoMVC tests. 
this will use a consistent naming convention.
=> use consistent names for benchmark test steps

resources/main.mjs, resources/params.mjs
Fixes #88. For now this just switches to the details view. I'd like to expand it over time so it has enough features to remove InteractiveRunner.html.
=> Initial dev mode param implementation

resources/todomvc/architecture-examples/backbone/dist/index.css, resources/todomvc/architecture-examples/backbone/package-lock.json, resources/todomvc/architecture-examples/backbone/package.json, resources/todomvc/architecture-examples/react-redux/package-lock.json, resources/todomvc/architecture-examples/react-redux/package.json, resources/todomvc/architecture-examples/react/package-lock.json, resources/todomvc/architecture-examples/react/package.json, resources/todomvc/vanilla-examples/javascript-es5/dist/base.css, resources/todomvc/vanilla-examples/javascript-es5/dist/index.css, resources/todomvc/vanilla-examples/javascript-es5/package-lock.json, resources/todomvc/vanilla-examples/javascript-es5/package.json, resources/todomvc/vanilla-examples/javascript-es6-webpack/package-lock.json, resources/todomvc/vanilla-examples/javascript-es6-webpack/package.json, resources/todomvc/vanilla-examples/javascript-es6/dist/index.css, resources/todomvc/vanilla-examples/javascript-es6/package-lock.json, resources/todomvc/vanilla-examples/javascript-es6/package.json
Clean-up pr to ensure all upgraded todomvc apps are using the same version of the todomvc styles:
```
"todomvc-app-css": "^2.4.2",
"todomvc-common": "^1.0.5"
```
@kara
=> Todomvc styles - consistent versions

resources/main.css
@camillobruni I thought I had pushed this up yesterday - no rush reviewing
=> Make details view fill available space

index.html, resources/main.css, resources/main.mjs, resources/todomvc/vanilla-examples/javascript-es5/src/store.js
This adds an alternative export format to easily get results into spreadsheets or other tools. PR also includes a few small cleanups with JSON exporting (removing unused download function), and also `npm run format`
=> Add CSV export

resources/todomvc/architecture-examples/preact/README.md, resources/todomvc/architecture-examples/react-redux/README.md, resources/todomvc/architecture-examples/react/README.md, resources/todomvc/architecture-examples/vue/README.md
=> TodoMVC preact readme update

resources/benchmark-runner.mjs, resources/main.mjs, tests/benchmark-runner-tests.mjs
style changes to avoid "dragging iframe" when resizing browser during tests
@kara
=> position iframe

resources/tests.mjs
Fixes #97
This only removes the steps and otherwise leaves the files as-is. I thought that there's value in keeping the (small) code supporting this in the stockcharts codebase, but please tell me if you'd like me to clean this up as well.
=> Remove Stockcharts-Canvas steps

resources/tests.mjs
=> workload test path udpates

resources/developer-mode.mjs, resources/main.css, resources/params.mjs
This also makes non-default params not frozen so they can be changed without a reload. Demo at https://devmode-2--speedometer-preview.netlify.app/?developerMode.
=> Additional developerMode controls

resources/developer-mode.mjs
* Update iterationCount slider label on input instead of change
* Allow ctrl/cmd click on a suite label in addition an input
Preview - https://devmode-3--speedometer-preview.netlify.app/?developerMode
=> Developer Mode UI improvements

resources/benchmark-runner.mjs, resources/params.mjs, resources/tentative/editors/tiptap.js
This prevents accidental modification in normal runs.
Drive-by-fix:
- Fix comment and run `npm run format`
=> Freeze params again in non-developerMode 

resources/benchmark-runner.mjs, resources/params.mjs, resources/tentative/editors/tiptap.js
- Add waitBeforeSync to set a timeout before running the sync step
- Change warmupBeforeSync to use 0 as default value
- Add more params comments
- Add common TestInvoker base class
=> Add param.waitBeforeSync

resources/params.mjs
I've accidentally used the wrong variable and broke parsing alltogether.
=> Fix params parsing

resources/tests.mjs
overlooked the tags in the tests...
=> Fix broken tests - add tags to nuxt app

resources/tests.mjs, resources/todomvc/architecture-examples/vue/src/App.vue
=> run format on all

resources/main.css, resources/main.mjs, resources/tests.mjs
With the default 10 iterations:
With 20:
=> Display iteration marker in progress bar

resources/developer-mode.mjs, resources/main.css, resources/tests.mjs
- Add Tags filtering buttons
- Update url with tag if a single tag can be used to represent the current selection
- Make sure auto-added tags are first in Tags and suite.tags
=> Developer Mode: Support filtering by tags

resources/benchmark-runner.mjs
With the addition of web components, the previous implementations of `Page.querySelector` and `Page.querySelectorAll `didn't let us target elements inside a shadow dom.
This pr augments those methods with an additional optional path array, that allows us to parse through nested web components.
`Page.getParent` is an internal helper function to get a reference to the parent of the requested element. This helper function is used in both: `Page.querySelector` and `Page.querySelectorAll`.
`PageElement.querySelector` is a new method that lets us retrieve an element from a wrapped node. 
Example - get input to enter a new todo:
```
const input = page.querySelector(".new-todo-input", ["todo-app", "todo-topbar"]);
for (let i = 0; i < numberOfItemsToAdd; i++) {
input.setValue(`Something to do …
```
=> Adjusting Page.querySelector / Page.querySelectorAll

resources/tests.mjs
Slipped through to use external text for the tests. 
One-liner!
=> TodoMVC - Web Components - udpate test text

resources/todomvc/vanilla-examples/javascript-web-components/dist/components/todo-app/todo-app.template.js, resources/todomvc/vanilla-examples/javascript-web-components/src/components/todo-app/todo-app.template.js
=> Remove extra todo-list element in javascript-web-components

resources/benchmark-runner.mjs, resources/params.mjs
=> Add param for shuffling suite order between runs

resources/main.mjs
This should simplify extracting metrics from the default page.
=> Add metrics getter

resources/benchmark-runner.mjs
@julienw PTAL. Extra line escaped my last PR.
=> Delete extra line

resources/tests.mjs
Reversing deletion steps for Lit and web compnent versions of the todomvc apps.
@kara
=> reverse lit/web components deletion steps

resources/developer-mode.mjs, resources/main.mjs
I find myself regularly confused that there is not "Start Test" button and this seems rather easy to fix.
=> Add "Start Test" button to developer menu

resources/tests.mjs
This PR interleaves the stand-alone and the complex dom tests.
Closes #340
=> Fix Complex vs. non-complex DOM subtests order

resources/developer-mode.mjs, resources/main.css, resources/main.mjs
This makes sure we don't have to add `#home` by default.
=> Allow empty hash for cleaner default URLs on the home screen

index.html, resources/main.mjs
Add a `data-title` to each section to update document.title.
=> Update document title

index.html
As per meeting agreement, let's remove the test-again button.
=> Remove "Test Again" button

README.md
Draft PR: to be landed ahead of launching
=> Remove experimental note from README.md

README.md
pr checks fail, since there's an empty first line in the readme file. 
@kara
=> run format command from root

Testing.md
Adding Microsoft Edge instructions to Testing.md, I forgot to update it in #382.
=> Update Testing.md to include Microsoft Edge

package-lock.json, package.json
The updated version has a few bug fixes and a newer version of `fake-timers`.
Nothing really spectacular, but it's nice to not fall too far behind on major versions.
See https://github.com/sinonjs/sinon/blob/main/CHANGES.md
=> chore: upgrade sinon to latest

experimental/todomvc-localstorage/README.md, experimental/todomvc-localstorage/dist/app.js, experimental/todomvc-localstorage/dist/base.css, experimental/todomvc-localstorage/dist/controller.js, experimental/todomvc-localstorage/dist/helpers.js, experimental/todomvc-localstorage/dist/index.css, experimental/todomvc-localstorage/dist/index.html, experimental/todomvc-localstorage/dist/model.js, experimental/todomvc-localstorage/dist/store.js, experimental/todomvc-localstorage/dist/template.js, experimental/todomvc-localstorage/dist/view.js, experimental/todomvc-localstorage/index.html, experimental/todomvc-localstorage/package-lock.json, experimental/todomvc-localstorage/package.json, experimental/todomvc-localstorage/scripts/build.js, experimental/todomvc-localstorage/src/app.js, experimental/todomvc-localstorage/src/controller.js, experimental/todomvc-localstorage/src/helpers.js, experimental/todomvc-localstorage/src/model.js, experimental/todomvc-localstorage/src/store.js, experimental/todomvc-localstorage/src/template.js, experimental/todomvc-localstorage/src/view.js, resources/benchmark-runner.mjs, resources/tests.mjs, resources/todomvc/vanilla-examples/javascript-es5/dist/store.js, resources/todomvc/vanilla-examples/javascript-es5/src/store.js
This pr switches the storage from in-memory to localStorage for todomvc-es5.
Scores snapshot:
| browser  | before | after |
| -------- | -------- | -------- |
| chrome  | 30.5 | 30.3 |
| firefox | 26.12 | 25.6 |
| safari | 25.5 | 25.3 |
@kara
=> Add local storage to todoMVC-es5

resources/developer-mode.mjs
- Move default onchange handler to createTimeRangeUI
- Add updateCallback to createCheckboxUI
=> Refactor developer-mode UI code

resources/params.mjs
- Move parsing to separate helper methods to main the `_copyFromSearchParams` method more readable.
- Add `Params.prototype._parseXXX` helper methods
=> Add Params parse helper methods

instructions.html
This is a cherry-pick of #402.
=> Remove duplicated word

resources/benchmark-runner.mjs
- Add `WakeLock` wrapper class around the [web-api](https://developer.mozilla.org/en-US/docs/Web/API/WakeLock)
- Use `WakeLock.aquire()` and `WakeLock.release()` in the benchmark runner
=> Use WakeLock

resources/score.svg
- Add more detailed label description
- Add custom spacing for legend
=> Score math: Add legend for variables

package-lock.json
Looks like #497 was missing the update to package-lock.json :-)
=> Update package-lock.json after package.json was changed
