WebKit/Speedometer

resources/benchmark-runner.mjs
Replace the continuation-based test running with an async-await loop over all suites and tests.
This also removes the necessity of the BenchmarkState class.
=> Async BenchmarkRunner and removing BenchmarkState

.gitignore, package-lock.json, package.json, tests/benchmark-runner-tests.mjs, tests/index.html
This PR does the following:
- Adds a `tests/` directory with:
- [`benchmark-runner-tests.mjs`](https://github.com/WebKit/Speedometer/compare/main...housseindjirdeh:benchmark-runner-tests-mocha?expand=1#:~:text=tests/benchmark%2Drunner%2Dtests.mjs) file that includes unit tests for `BenchmarkRunner`
- [`tests/index.html`](https://github.com/WebKit/Speedometer/compare/main...housseindjirdeh:benchmark-runner-tests-mocha?expand=1#diff-90b511c392b35b916f8651ba3b27fea4341761dd54aedaec91c52a757e545667) file to run and display tests all in the browser (note: you'll have to spin up a local server to prevent module files from being blocked by CORS)
---
=> Adds unit tests for `BenchmarkRunner` using Mocha

tests/index.html, tests/run.mjs
@bgrins pointed out that we introduced some flakiness in our test by adding a timeout in addition to using the "wait" function from the web driver. 
The approach that I am suggesting here, is to take advantage of the "complete" callback from mocha in the browser, dispatching an even on the window object and listening for that event through "executeAsyncScript" from the web driver, which returns a callback with the stats from Mocha. This gives us a bridge between both scopes and returns the mocha stats results that we need to make the assertions.
=> Remove wait from selenium test

resources/benchmark-runner.mjs
- Directly use performance.now and performance.mark
- Reduce a bit of overhead
- Use separate variables for sync / async time measurements to make the code more clear
- Optimize _appendFrame() code by using local variables
=> Minor runner updates

resources/interactive.mjs, resources/main.mjs, resources/params.mjs, resources/tests.mjs
- Add support for filtering multiple suites
- Support startAutomatically in the default runner
- Fix displaying detailed results with unit=ms
- More error messages on invalid url-params
- Add Suites.enable function instead of two separate implementations per runner
=> Use params everywhere

tests/benchmark-runner-tests.mjs
The method has been removed since we're now using performance.now directly.
=> Remove _writeMark test

resources/benchmark-runner.mjs, tests/benchmark-runner-tests.mjs
This would allow profiler tools to show user timing ranges and makes it easier to focus in on different portions of tests.
@camillobruni what do you think about this? My understanding of this API from https://developer.mozilla.org/en-US/docs/Web/API/Performance/measure is that the `duration` object functionally the same as the existing subtractions using performance.now()
=> WIP - use performance.measure api instead of manually tracking with performance.now()

index.html, resources/main.css, resources/main.mjs
- Remove history state 
- Prevent accidentally restarting benchmark in `startBenchmark()`
- Add "home" link to about page
- Add explicit logic in `_showSection(...)` for selecting the allowed views
- Use a-href that point to the shown section
- Use CSS rules to show/hide sections (in preparation for making the details full-width)
Visible change: All urls now have a explicit hash (default is `#home`)
=> Use window.location.hash for navigation

.eslintrc, index.html, resources/benchmark-runner.mjs, resources/interactive.mjs, tests/server.mjs
A small adjustment to our eslint rules, to hopefully address the issue of: 
"No curly braces around single line statements."
note: the format command always runs prettier before eslint, since eslint needs to correct some prettier formatting rules that we can't control. 
Hope this gets us closer to the desired style guide.
=> Formatting adjustment

index.html, resources/main.css, resources/main.mjs
This PR makes each runner section independent to allow custom sizes.
This is in preparation for PR #42 to allow more space for the details view.
- Move border layout from `main` to each `section`
- Copy logo into every `section`
- Use grid-layout for header/content/footer in about and details view
=> Allow custom section sizes

resources/benchmark-runner.mjs, tests/benchmark-runner-tests.mjs
=> emit start-suite and end-suite performance marks outside of the timed region

resources/todomvc/architecture-examples/backbone/package.json, resources/todomvc/architecture-examples/emberjs/package.json, resources/todomvc/architecture-examples/preact/package.json, resources/todomvc/architecture-examples/react-redux/package.json, resources/todomvc/architecture-examples/react/package.json
It got confusing with "dev" and "start" scripts to spin up the local dev environment. 
This cleanup uses a consistent script name ("dev") for all updated workloads. 
@kara
=> Todomvc scripts cleanup

resources/todomvc/architecture-examples/angular/dist/index.html, resources/todomvc/architecture-examples/angular/src/index.html
This allows the benchmark to be ran inside another directory in a local HTTP server.
=> Don't specify the base URL as an absolute path.

resources/benchmark-runner.mjs, resources/main.css
This should improve the state of #37.
Before:
After:
=> reduce flashing by setting a light background to better match the content of the tests

resources/benchmark-runner.mjs, tests/benchmark-runner-tests.mjs
- Use more `performance.mark` for suites.
- Pre-build the mark strings upfront
=> Use more performance.mark for suites

resources/tentative/charts/dist/assets/plot-1a97ddda.js, resources/tentative/charts/dist/observable-plot.html, resources/tentative/charts/observable-plot.html, resources/tentative/charts/observable-plot.js, resources/tests.mjs
This is a follow-up to #144.
In Firefox I see more work related to styling in the async marker when configured to "20".
What do you think @rniwa?
=> Make the number of airports per group configurable and use it in tests

resources/statistics.mjs
Fixes https://github.com/WebKit/Speedometer/issues/138 This allows the test runner to support an iteration count higher than 100.
=> Make confidenceIntervalDelta work with more than 100 degrees of freedom.

resources/developer-mode.mjs, resources/main.css, resources/main.mjs, resources/tests.mjs
Fixes #158. Preview at https://devmode-ui--speedometer-preview.netlify.app/?developerMode
=> add a basic developer mode ui on the main runner

resources/tests.mjs
To avoid to run into the safari limitation, I adjusted the test: 
`SecurityError: Attempt to use history.replaceState() more than 100 times per 30 seconds.`
Details:
With this change we limit the amount of history api calls.
Snapshot from chrome:
before change:
after change:
=> News-site: adjust test steps

resources/tests.mjs
this might fix this issue: https://github.com/WebKit/Speedometer/issues/179
update:
simplified test and removed toast close action on the homepage.
=> newssite - potential fix for test

resources/benchmark-runner.mjs, tests/benchmark-runner-tests.mjs
This class abstracts away two nested setTimeout calls and requestAnimationFrame.
=> Refactor test callbacks into TestInvoker class.

resources/benchmark-runner.mjs, tests/benchmark-runner-tests.mjs
Adding more markers to simplify checking if work is measured
- Add iteration-X for each runner iteration
- Add runner-prepare and runner-finalize to annotate time it takes for adding/removing the iframe
- Use suite-X-prepare
=> Add more markers

resources/main.css, resources/metric-ui.mjs
Make sure we can easily copy the whole detailed results page as formatted text.
- Only toggle charts when clicking on charts
- Don't copy chart legend bullet
- Don't copy chart axis labels
Drive-by-fix:
- Put abbreviation ellipsis for chart legends at the beginning so we don't hide the more important metric suffix
=> Better copy-support for detailed results table

resources/benchmark-runner.mjs, resources/params.mjs
This will allow us to evaluate the impact of using rAF vs. timer with regards to CPU throttling.
=> Add warmupBeforeSync parameter, which triggers 100ms of infinite loop before each sync step.

resources/todomvc/vanilla-examples/javascript-es5/dist/view.js, resources/todomvc/vanilla-examples/javascript-es5/src/view.js
In this PR I replaced the use of innerHTML by 2 alternatives as found in some newer libraries: `DOMParser` and `range.createContextualFragment`, each in a different benchmark implementation.
__Update__: In the current version of the patch, only `DOMParser` is used.
This follows the quick research I made in https://docs.google.com/document/d/1sHjNPpu1HgnmLmrN3ae9m_ATkI5FEuAIJZahLvrE7-A/edit?usp=sharing.
You can use this URL to run these changes on your computer:
https://replace-innerhtml--speedometer-preview.netlify.app/?suite=TodoMVC-JavaScript-ES5,TodoMVC-JavaScript-ES6,TodoMVC-JavaScript-ES6-Webpack
ES6-Webpack hasn't changed but I included it in the above link as a comparison.
~~Based on research we could also add a template + innerHTML test as in `lit-html`, but because we also plan …
=> Replace innerHTML by DOMParser in a workload

index.html, resources/main.css
This will make it easier to immediately distinguish this from Speedometer 2.X
I've double checked to match the kerning of the rasterized speedometer logo with the original Futura-Medium font.
=> Show version number

resources/tests.mjs
#97 
There are several goals for this patch:
* make the workload more realistic
* make this test faster.
I decided to reduce the amount of events sent for the "pan the chart" step, and cut down the work in the "zoom the chart" step.
Now, for the "pan the chart" step, instead of moving the mouse 1000 times, it's now 50 times.
For the "zoom in" step, instead of 50 times, it's now 15 times.
[base branch from #176](https://stabilize-react-stockcharts--speedometer-preview.netlify.app/?suite=React-Stockcharts-SVG)
[deploy preview](https://split-react-stockcharts--speedometer-preview.netlify.app/?suite=React-Stockcharts-SVG)
Firefox before/after
Chrome before/after
Chrome seems to benefit more than Firefox from this change, but we think it's a more realistic workload.
In more details: Chrome …
=> Reduce the react stockcharts steps

resources/developer-mode.mjs, resources/main.css
- Enlarge clickable targets (title and list items)
- Make buttons fill space horizontally
- Match border radius with other runner buttons
=> Developer Mode Improvements

resources/main.css
Some colleagues complained it looks not so nice (despite being the normal spacing). 
Drive-by-fix: Add Roboto as slightly better alternative font.
Before:
After:
=> Reduce version number letter spacing

resources/editors/codemirror.html
We can undo this change once Safari / WebKit adds the support for requestIdleCallback.
=> Undefine requestIdleCallback in the code mirror test for consistency.

resources/editors/codemirror.html, resources/editors/codemirror.js, resources/editors/dist/assets/codemirror-521de7ab.js, resources/editors/dist/assets/tiptap-95a40ba8.js, resources/editors/dist/codemirror.html, resources/editors/dist/tiptap.html, resources/editors/tiptap.html, resources/editors/tiptap.js, resources/tests.mjs
This is a tentative to reduce the variance in Chrome. There's still a variance for the first run especially, but the create step doesn't contribute to it anymore. It was a quite short step so I believe it makes sense. 
I moved the create step in the "long" step. I had to refactor a few things in the workloads because of this.
[main branch](https://speedometer-preview.netlify.app/?suite=Editor-Codemirror,Editor-Tiptap)
[main branch with raf](https://speedometer-preview.netlify.app/?suite=Editor-Codemirror,Editor-Tiptap&measurementMethod=raf)
[this patch's preview](https://group-more-editor-steps--speedometer-preview.netlify.app/?suite=Editor-Codemirror,Editor-Tiptap)
[this patch's preview with raf](https://group-more-editor-steps--speedometer-preview.netlify.app/?suite=Editor-Codemirror,Edi …
=> [Editors] Group the Create step into the next step

resources/tests.mjs
This is for preparing the move of the charts workload out of tentative.
[this pull request](https://make-charts-more-stable--speedometer-preview.netlify.app/?suite=Charts-Observable-plot,Charts-Chartjs)
[this pull request with raf measurements](https://make-charts-more-stable--speedometer-preview.netlify.app/?suite=Charts-Observable-plot,Charts-Chartjs&measurementMethod=raf)
[current main](https://speedometer-preview.netlify.app/?suite=Charts-Observable-plot,Charts-Chartjs)
[current main with raf measurements](https://speedometer-preview.netlify.app/?suite=Charts-Observable-plot,Charts-Chartjs&measurementMethod=raf)
On my machine, this seems to make the workloads more stable, both in Chrome and Firefox. Tell me what you think @rniwa @flashdesignory !
=> [charts] Group substeps to make them more stable

resources/tentative/perf.webkit.org/public/v3/index.html, resources/tests.mjs
This makes the benchmark results more consistent when re-running it in the same tab.
=> Move the initial glyph cache cost out of the measured part of the perf dashboard workload.

resources/todomvc/architecture-examples/lit/dist/index.html, resources/todomvc/architecture-examples/lit/package.json
Fixes https://github.com/WebKit/Speedometer/issues/269
=> Generate lit/dist/index.html

package.json
`npm run server` will now run a local server with caching files.
This is more realistic for local benchmarking, while `npm run dev` keeps on the non-caching behavior which is nicer for developing the benchmark.
=> add npm run server to run caching server

resources/tests.mjs
This is the follow up pr for https://github.com/WebKit/Speedometer/pull/259.
added helper function to assign translations.
todomvc - es5 uses Japanese
todomvc - es6 uses Russian
Happy to swap workloads for the translations, but these seemed reasonable choices.
@kara
=> use translations in todomvc tests

resources/benchmark-runner.mjs, tests/benchmark-runner-tests.mjs
This makes the score runs/s, which is pretty neat.
=> Simplify the score calculation by replacing 60 / 50 by 1.

resources/todomvc/architecture-examples/react-complex/readme.md
Right now, there is a `resources/todomvc/architecture-examples/react-complex/readme.md` and a `resources/todomvc/architecture-examples/react-complex/README.md`. Deleting the lowercase version.
=> Delete duplicated React Complex DOM README

resources/developer-mode.mjs, resources/tests.mjs
This PR:
- Adds all the complex DOM workloads to `tests.mjs` under the `complex` tag.
- Sets the disabled flag to `true` for all complex-DOM variations except React-Complex-DOM.
- Adds a new tag `complex-default` for the workloads that the group agreed should eventually be enabled by default.
- Makes a small logic change to not add the `default` tag for the disabled tests.
[Hosted version](https://lpardosixtosms.github.io/Speedometer)
=> Add complex DOM workloads to tests.mjs disabled by default

resources/todomvc/vanilla-examples/javascript-web-components/dist/components/todo-item/todo-item.component.js, resources/todomvc/vanilla-examples/javascript-web-components/dist/components/todo-list/todo-list.component.js, resources/todomvc/vanilla-examples/javascript-web-components/src/components/todo-item/todo-item.component.js, resources/todomvc/vanilla-examples/javascript-web-components/src/components/todo-list/todo-list.component.js
issue https://github.com/WebKit/Speedometer/issues/313
changed this.id => this["item-id"], this.title => this["item-title"] and this.completed => this["item-completed"].
If the brackets are bothersome, I could change it to this.itemid, this.itemtitle, ect... just personal preference to use the above. 
chrome before:
chrome after:
firefox before:
firefox after:
safari before:
safari after:
edge before:
edge after:
@kara
=> todomvc web-components, change title, id & completed attributes on item component

resources/main.css
=> Fix developerMode layout

resources/tests.mjs
Previously, we were transforming it into a set. This was giving problems in a later condition, so that no message/debugInfo were defined, and the user would get an alert with the message "undefined".
Now the set stays local to the code block where it's used, so that the parameter variable "tags" is an array for the whole function, for more consistency with the "names" variable.
=> Keep the parameter 'tags' as an array in the body of the function

resources/tests.mjs
- Angular
- JavaScript-ES6-Webpack
- Lit
- Preact
- React
- Svelte
- WebComponents
- JavaScript-ES5
- React-Redux
- Backbone
- Vue
- jQuery
=> Enable complex DOM benchmarks execution in official speedometer run

resources/todomvc/architecture-examples/backbone-complex/package-lock.json, resources/todomvc/architecture-examples/jquery-complex/package-lock.json, resources/todomvc/architecture-examples/lit-complex/package-lock.json, resources/todomvc/architecture-examples/preact-complex/package-lock.json, resources/todomvc/architecture-examples/react-complex/package-lock.json, resources/todomvc/architecture-examples/react-redux-complex/package-lock.json, resources/todomvc/architecture-examples/vue-complex/package-lock.json, resources/todomvc/vanilla-examples/javascript-es5-complex/package-lock.json, resources/todomvc/vanilla-examples/javascript-es6-webpack-complex/package-lock.json, resources/todomvc/vanilla-examples/javascript-es6-webpack-complex/package.json
Addressing a comment.
https://github.com/WebKit/Speedometer/pull/315#discussion_r1434121415
jsdom was removed as a devDependency but the package-lock.jsons were not regenerated.
=> Regenerate package-lock.json

.eslintignore, .eslintrc, .prettierignore, package.json, resources/developer-mode.mjs, resources/newssite/news-next/.eslintrc.json
Here are a few fixes for small problems I found while working on the project lately.
Commits should be fairly independent so feel free to look at them separately.
1. Remove tentative/ from the ignore lists. Indeed there's no tentative workload anymore, but working on some on local branches I find it easier that prettier and eslint are not disabled on these directories.
2. This makes tsx files checked by the eslint, as well as mirror the check with the fix configuration.
3. It's good practice to put `root: true` on the top level eslint configuration file. Reference: https://eslint.org/docs/latest/use/configure/configuration-files#cascading-and-hierarchy
4. While running eslint, I found this false positive about the next eslint plugin. It was due to a misconfiguration in the newssite-next …
=> Small lint-related fixes

resources/main.mjs
Temporarily set the `#home` hash before clearing it to ensure proper visibility of the home section.
=> Fix navigation for Firefox

resources/main.mjs
PR #349 combined with #353  accidentally introduced a navigation recursion that needs fixing for the developerMode to work properly.
=> Fix navigation recursion

resources/todomvc/architecture-examples/jquery-complex/dist/app.js, resources/todomvc/architecture-examples/jquery-complex/dist/index.html, resources/todomvc/architecture-examples/jquery/dist/app.js, resources/todomvc/architecture-examples/jquery/dist/index.html, resources/todomvc/architecture-examples/jquery/index.html, resources/todomvc/architecture-examples/jquery/package.json, resources/todomvc/architecture-examples/jquery/src/app.js
Switched 'id' to 'class' for 'clear-completed'.
This is necessary for the css rules to apply correctly.
Fixes issue https://github.com/WebKit/Speedometer/issues/363
@kara
=> TodoMVC jQuery: fix clear completed button

.github/workflows/test.yml, about.html, resources/todomvc/architecture-examples/angular/angular.json
I noticed that the github action runs the formatter, but doesn't check that anything was actually reformatted as a result. So it was always successful.
To fix the issue, my strategy is to run a special form of `git status` whose output won't change over time. If the output is empty, this means that there's no change. Otherwise the action outputs some helpful diagnostics.
Here are examples of output:
Failing: https://github.com/WebKit/Speedometer/actions/runs/7920439286/job/21623479161?pr=374
Successful: https://github.com/WebKit/Speedometer/actions/runs/7920372392/job/21623262244?pr=374
=> Make the github action linter step fail in the case of issues

package.json, tests/run.mjs
Add edge to the supported browsers for testing. This PR doesn't change the tests run on the github pipelines.
=> Enable integration testing in Edge.

index.html, resources/main.css, resources/main.mjs
Fixes #394.
This changes how section visibility is controlled. All sections are still `display:none` by default.
Rather than becoming `display:block` when they match `:target`, they now become `display:block` if their ID matches the value of the root element's `data-visible-section` attribute - we hardcode the four section names "home", "running", "summary" and "details".
This lets us default to the home section just by setting `<html data-visible-section="home">` in index.html, and we can avoid the `:has` selector.
Now Speedometer can run in older browsers which don't support `:has`.
=> Avoid :has selector in CSS.

.github/workflows/test.yml, package.json, tests/run.mjs
This change allows the npm test scripts to also run on windows machines.
The PR:
- switches the way the browser is defined when running tests. Initially, the browser was determined via environment variables `(e.g., BROWSER=chrome node tests/run.mjs)`. However, this PR alters the approach to use command line arguments instead `(e.g., node tests/run.mjs --browser chrome)`.
- The Run tests step in the ci workflow now uses the npm scripts
- make `npm run format` work as well.
=> Fix Cross-platform issue with npm script

.github/workflows/test.yml
Looks like macos-latest does not include Firefox. 
Manually running `brew install --cask firefox` on the firefox test job solves the problem.
=> Manually install Firefox on macos-latest image

index.html, resources/benchmark-runner.mjs, resources/main.mjs, resources/metric.mjs
The metric's "geomean" aggregate value can be easily confused with the top-level Geomean metric (issue #407).
- Don't serialize "geomean" in the JSON data
- Add descriptions to Score, Geomean, and Iteration metrics that are serialized in the JSON data
- Make the detail view titles more descriptive
=> Deconfuse Geomean Metric and geomean aggregate value

resources/benchmark-runner.mjs
The offending `new Promise(async ...)` code was already removed in 19184dc69432fa7e511e13f3318c8c3e1acd28ca but this linting comment remained.
=> Remove obsolete eslint ignore

Development.md, package.json, resources/charts/README.md, resources/editors/README.md
Port 7000 is occupied by default on macOS.
This also makes it simpler how to customize it
(use env var instead of hardcoded in the package.json)
https://github.com/WebKit/Speedometer/issues/325
=> Change default port to 8900 

resources/benchmark-runner.mjs, tests/benchmark-runner-tests.mjs
Move Suite-related code to a separate SuiteRunner class.
This happens in preparation for async and remote suites where it will be cleaner to handle the code paths independently instead of adding more functionality to the BenchmarkRunner class.
=> Split off SuiteRunner class

resources/benchmark-runner.mjs
Use a lookup dict for more future-proof way to look up a test invoker class.
=> Add more flexible TEST_INVOKER_LOOKUP

resources/benchmark-runner.mjs, tests/benchmark-runner-tests.mjs
We can migrate some of the measuredValue logic directly to the SuiteRunner and simplify the code a bit.
Additionally this will allow us to generate more flexible metrics in the future.
=> Add local results variable to SuiteRunner

tests/benchmark-runner-tests.mjs, tests/index.html, tests/run.mjs
Currently, if tests fail when running `npm run test:chrome`, ect we don't get a good reporting in the node console. 
Especially, if a test fails, we don't get any details.
current pass:
current fail:
A cleanup can give us similar (simplified) reporting, as the browser window displays.
new pass:
new fail:
=> Test Runner cleanup - for our internal tests

resources/benchmark-runner.mjs, resources/test-invoker.mjs
To prepare further for the remote workloads / postMessage feature, I'd like to separate out the test invokers from the benchmark-runner. This will reduce duplicate code, since workloads will re-use (import) the same test invoker classes to run the tests themselves. 
Since the test invokers are self-contained now, I am passing in the params object, which the classes rely on.
=> split TestInvokerClass into a separate file

resources/benchmark-runner.mjs, resources/suite-runner.mjs, resources/test-runner.mjs, tests/benchmark-runner-tests.mjs
- move SuiteRunner class into a separate file
- create a new TestRunner class, which a remote workload could consume in the future
- rename _runTestAndRecordResults to TestRunner.runTest()
- create class methods for functions used in the runSync & measureAsync functions
=> Runner Cleanup: SuiteRunner & TestRunner classes

resources/main.mjs, resources/suite-runner.mjs
This is needed to allow for remote workloads.
=> Make the progress bar track indivisual suites, not indivisual steps.

resources/developer-mode.mjs, resources/shared/params.mjs, resources/shared/test-invoker.mjs
requestAnimationFrame based measurement for 3.0 and found no issues.
=> Delete the timer based measurement since we've switched over to

tests/index.html, tests/run.mjs
Instead of triggering the tests from the outside, we can always directly start the mocha runner in `tests/index.html`.
The selenium driver now syncs on either `globalThis.testResults` being there or the `test-complete` event.
This way we should be able to reliably run the tests both via selenium and the browser.
=> Auto run unittests in tests/index.html

netlify.toml
This configures the same headers as for https://browserbench.org/Speedometer3.0/.
I prefered to use `netlify.toml` over a `_headers` file to make it more obvious what this file is for.
Documentation is in https://docs.netlify.com/routing/headers/#syntax-for-the-netlify-configuration-file
Note that this doesn't apply until it's committed to the main branch (I think).
=> Add a netlify configuration file

index.html, resources/benchmark-runner.mjs, resources/metric.mjs
The metric's "geomean" aggregate value can be easily confused with the top-level Geomean metric (issue #407).
- Don't serialize "geomean" in the JSON data
- Add descriptions to Score, Geomean, and Iteration metrics that are serialized in the JSON data
- Make the detail view titles more descriptive
=> Release/3.1 - merge 408: Deconfuse Geomean Metric and geomean aggregate value

index.html, resources/main.css
I accidentally ran the wrong version locally and would like to make it more obvious which branch we're on.
Happy to take suggestions here :).
=> Use "next" as version ID on the main branch

resources/perf.webkit.org/public/v3/bundled-scripts.js, resources/perf.webkit.org/public/v3/index.html, resources/perf.webkit.org/public/v3/pages/page-router.js
This results in nothing interesting being measured during the sync phase, and the resulting rendering update (during the async phase) not including the change.
Change the test to manually and synchronously trigger the onhashchange() callback, and change the page content to detect and omit duplicate events.
Crossbench results before/after the change:
```
label                                       macos.arm64.local_0    macos.arm64.local_1    macos.arm64.local_2
browser                                     Firefox                Safari                 Google Chrome
version                                     135.0                  18.3 (20620.2.4)       133.0.6943.99
os                                          macos 15.3.1 arm64     macos 15.3.1 arm64     macos 15.3.1 arm64
device …
```
=> Perf-Dashboard.Render sync phase sets location.hash, but the actual DOM modifications happen asynchronously in the onhashchange() callback.

resources/benchmark-runner.mjs
* Add WakeLock wrapper class around the web-api to keep the screen unlocked during benchmark runs
* Use WakeLock.aquire() and WakeLock.release() in the benchmark runner
=>  Release/3.1 - merge 491: Use WakeLock

resources/main.mjs
Ensure the document title when visiting the main page for version 3.1:
Before
After
=> Release/3.1 - Ensure the benchmark version text in the index page title

package.json
We've changed this to 8080 on the main branch already, would be nice to have the same for easier local testing in the future.
=> Release/3.1 - Use 8080 as default address for local test server

resources/shared/params.mjs, tests/index.html, tests/unittests/params.mjs
- Add better viewport, suite and tags handling
- Add basic Params unittests
=> Improve Params.toSearchParamsObject

resources/developer-mode.mjs, resources/shared/params.mjs, tests/unittests/params.mjs
Remove duplicated code and directly use `Params.prototype.toSearchParams()`.
Now the Params class is the centralized place to implement the serialization logic.
=> Use Params.prototype.toSearchParams() in developer-mode.mjs

resources/benchmark-runner.mjs, resources/developer-mode.mjs, resources/shared/helpers.mjs, resources/shared/params.mjs, resources/shared/test-runner.mjs
Currently we have two different modes in which we force layout
- `getBoundingClientRect` used by default in the benchmark runner and tests
- `elementFromPoint` used in the remote workloads
This PR adds a new `layoutMode` param to switch between the two modes.
=> Customize Force Layout
